name: pembe_oyun
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  change_app_package_name: ^1.5.0
  audioplayers: ^6.5.1
  shared_preferences: ^2.5.4
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

# İkon Ayarları (Burada tek bir tane olmalı)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/BrainGlitch_Logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/BrainGlitch_Logo.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/arrow.png
    - assets/pause.png
    - assets/gift.png
    - assets/audio/
    - assets/images/